apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: todo-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: arunkumarcarch/todo_web_image:32ccebd313a53fa5d3e07a9ed94b9518458ec7e8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            # - containerPort: 3000
          # env:
          #   - name: REACT_APP_API_URL
          #     value: "http://api.todo-lab.svc.cluster.local:8000"